name: isupply_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  get: ^4.7.2
  hive: ^2.2.3
  faker_dart: ^0.2.2
  flutter_svg: ^2.2.0
  dropdown_search: ^6.0.2
  flutter_slidable: ^4.0.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  modal_side_sheet: ^0.0.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  build_runner: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
