name: isupply_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7
  faker_dart: ^0.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  responsive_framework: ^1.5.1
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/
    - .env
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
